# Generated by Django 4.0.3 on 2022-08-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastroCliente',
            new_name='Pessoa',
        ),
    ]
