# Generated by Django 4.0.3 on 2022-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_cadastrocliente_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
